nohup python ../correlation_between_uATGgainloss_variant.py ../uAUG_gained_uORF_2L.recode.vcf ../uAUG_lost_uORF_2L.recode.vcf /gpfs2/liucl/lcl/analysis/isofemale_line/demographic/sample_list_new/CN.list CN_gainloss_correlation_2L.txt &
nohup python ../correlation_between_uATGgainloss_variant.py ../uAUG_gained_uORF_2R.recode.vcf ../uAUG_lost_uORF_2R.recode.vcf /gpfs2/liucl/lcl/analysis/isofemale_line/demographic/sample_list_new/CN.list CN_gainloss_correlation_2R.txt &
nohup python ../correlation_between_uATGgainloss_variant.py ../uAUG_gained_uORF_3L.recode.vcf ../uAUG_lost_uORF_3L.recode.vcf /gpfs2/liucl/lcl/analysis/isofemale_line/demographic/sample_list_new/CN.list CN_gainloss_correlation_3L.txt &
nohup python ../correlation_between_uATGgainloss_variant.py ../uAUG_gained_uORF_3R.recode.vcf ../uAUG_lost_uORF_3R.recode.vcf /gpfs2/liucl/lcl/analysis/isofemale_line/demographic/sample_list_new/CN.list CN_gainloss_correlation_3R.txt &
nohup python ../correlation_between_uATGgainloss_variant.py ../uAUG_gained_uORF_4.recode.vcf ../uAUG_lost_uORF_4.recode.vcf /gpfs2/liucl/lcl/analysis/isofemale_line/demographic/sample_list_new/CN.list CN_gainloss_correlation_4.txt &
nohup python ../correlation_between_uATGgainloss_variant.py ../uAUG_gained_uORF_X.recode.vcf ../uAUG_lost_uORF_X.recode.vcf /gpfs2/liucl/lcl/analysis/isofemale_line/demographic/sample_list_new/CN.list CN_gainloss_correlation_X.txt &

nohup python ../correlation_between_uATGgainloss_variant_homo.py ../uAUG_gained_uORF_2L.recode.vcf ../uAUG_lost_uORF_2L.recode.vcf /gpfs2/liucl/lcl/analysis/isofemale_line/demographic/sample_list_new/CN.list CN_gainloss_correlation_homo_2L.txt &
nohup python ../correlation_between_uATGgainloss_variant_homo.py ../uAUG_gained_uORF_2R.recode.vcf ../uAUG_lost_uORF_2R.recode.vcf /gpfs2/liucl/lcl/analysis/isofemale_line/demographic/sample_list_new/CN.list CN_gainloss_correlation_homo_2R.txt &
nohup python ../correlation_between_uATGgainloss_variant_homo.py ../uAUG_gained_uORF_3L.recode.vcf ../uAUG_lost_uORF_3L.recode.vcf /gpfs2/liucl/lcl/analysis/isofemale_line/demographic/sample_list_new/CN.list CN_gainloss_correlation_homo_3L.txt &
nohup python ../correlation_between_uATGgainloss_variant_homo.py ../uAUG_gained_uORF_3R.recode.vcf ../uAUG_lost_uORF_3R.recode.vcf /gpfs2/liucl/lcl/analysis/isofemale_line/demographic/sample_list_new/CN.list CN_gainloss_correlation_homo_3R.txt &
nohup python ../correlation_between_uATGgainloss_variant_homo.py ../uAUG_gained_uORF_4.recode.vcf ../uAUG_lost_uORF_4.recode.vcf /gpfs2/liucl/lcl/analysis/isofemale_line/demographic/sample_list_new/CN.list CN_gainloss_correlation_homo_4.txt &
nohup python ../correlation_between_uATGgainloss_variant_homo.py ../uAUG_gained_uORF_X.recode.vcf ../uAUG_lost_uORF_X.recode.vcf /gpfs2/liucl/lcl/analysis/isofemale_line/demographic/sample_list_new/CN.list CN_gainloss_correlation_homo_X.txt &
