python ../sum_pnt_cov.py ribo_pnt_coverage/dmel_em_0_2h.Psite.trans.bed all_uorf_cnt/all_uorf_tpos.txt >all_uorf_cnt/dmel_em_0_2h.Psite_uorf_cnt.bed
python ../sum_pnt_cov.py ribo_pnt_coverage/dmel_em_12_24h.Psite.trans.bed all_uorf_cnt/all_uorf_tpos.txt >all_uorf_cnt/dmel_em_12_24h.Psite_uorf_cnt.bed
python ../sum_pnt_cov.py ribo_pnt_coverage/dmel_em_2_6h.Psite.trans.bed all_uorf_cnt/all_uorf_tpos.txt >all_uorf_cnt/dmel_em_2_6h.Psite_uorf_cnt.bed
python ../sum_pnt_cov.py ribo_pnt_coverage/dmel_em_6_12h.Psite.trans.bed all_uorf_cnt/all_uorf_tpos.txt >all_uorf_cnt/dmel_em_6_12h.Psite_uorf_cnt.bed
python ../sum_pnt_cov.py ribo_pnt_coverage/dmel_female_body1.Psite.trans.bed all_uorf_cnt/all_uorf_tpos.txt >all_uorf_cnt/dmel_female_body1.Psite_uorf_cnt.bed
python ../sum_pnt_cov.py ribo_pnt_coverage/dmel_female_body2.Psite.trans.bed all_uorf_cnt/all_uorf_tpos.txt >all_uorf_cnt/dmel_female_body2.Psite_uorf_cnt.bed
python ../sum_pnt_cov.py ribo_pnt_coverage/dmel_female_head.Psite.trans.bed all_uorf_cnt/all_uorf_tpos.txt >all_uorf_cnt/dmel_female_head.Psite_uorf_cnt.bed
python ../sum_pnt_cov.py ribo_pnt_coverage/dmel_larva.Psite.trans.bed all_uorf_cnt/all_uorf_tpos.txt >all_uorf_cnt/dmel_larva.Psite_uorf_cnt.bed
python ../sum_pnt_cov.py ribo_pnt_coverage/dmel_male_body1.Psite.trans.bed all_uorf_cnt/all_uorf_tpos.txt >all_uorf_cnt/dmel_male_body1.Psite_uorf_cnt.bed
python ../sum_pnt_cov.py ribo_pnt_coverage/dmel_male_body2.Psite.trans.bed all_uorf_cnt/all_uorf_tpos.txt >all_uorf_cnt/dmel_male_body2.Psite_uorf_cnt.bed
python ../sum_pnt_cov.py ribo_pnt_coverage/dmel_male_head.Psite.trans.bed all_uorf_cnt/all_uorf_tpos.txt >all_uorf_cnt/dmel_male_head.Psite_uorf_cnt.bed
python ../sum_pnt_cov.py ribo_pnt_coverage/dmel_pupa.Psite.trans.bed all_uorf_cnt/all_uorf_tpos.txt >all_uorf_cnt/dmel_pupa.Psite_uorf_cnt.bed
